add meta tag and favicon
Design-and-Code/Design-and-Code pull request #22
Opened 2021-10-26 18:19 UTC by frankiefab100

Fixes #10

2021-11-03 10:29 UTC, thuongtruong1009 requested changes

2021-11-03 10:29 UTC, thuongtruong1009 commented on public/index.html
> +    <meta name="title" content="Design And Code" />
In the same that, you also write like <title>Design And Code</title>
But you already exist title tag below, so you do not need to display this line

2021-12-16 15:14 UTC, frankiefab100 commented
@thuongtruong1009 it has been fixed.

2021-12-17 02:00 UTC, thuongtruong1009 approved these changes

2022-04-12 16:07 UTC, closed without merging