fix: Meta Tags and Favicons
Design-and-Code/Design-and-Code pull request #72
Opened 2023-02-28 16:11 UTC by Alkaison

**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] The code related to the changes has been properly commented

**What kind of change does this PR introduce?** _(select / add custom)_

- feature: adds meta tags and new favicons 

**What is the current behavior?** _(link the issue here)_

- Fixes #10 
- New Meta Tags 
- New favicons with manifest 

**What is the new behavior?**

- Meta tags will help in increasing the SEO of the website.

2023-02-28 16:57 UTC, Alkaison commented
- Added Meta Tags 
- Added new Favicons for different devices with manifest

Here's the list of meta tags I have implemented:

```HTML
          <meta name="theme-color" content={theme.palette.primary.main} />
          <link rel="shortcut icon" href="favicon.ico" />
          <meta name="emotion-insertion-point" content="" />
          {/* <!-- Primary Meta Tags --> */}
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          {/* <!-- Facebook --> */}
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://www.designandcode.us/" />
          <meta property="og:title" content="Home | Design and Code" />
          <meta property="og:description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          <meta property="og:image" content="static\branding-logos\branding-transparent-logo.svg" />
          {/* <!-- Twitter --> */}
          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://www.designandcode.us/" />
          <meta property="twitter:title" content="Home | Design and Code" />
          <meta property="twitter:description" content="Design and Code a global community where anyone can learn and network with fellow developers and designers." />
          <meta property="twitter:image" content="static\branding-logos\branding-transparent-logo.svg" />
          {/* <!-- SEO Tags --> */}
          <meta name="language" content="EN" />
          <meta property="og:locale" content="en" />
          <meta property="og:type" content="website" />
          <meta property="og:site_name" content="Home | Design and Code" />
          <meta name="url" content="https://www.designandcode.us/" />
          <meta name="coverage" content="Worldwide" />
          <meta name="distribution" content="Global" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta content="yes" name="apple-touch-fullscreen" />
          <meta name="copyright" content="Home | Design and Code" />
          {/* <!--
              Notice the use of %PUBLIC_URL% in the tags above.
              It will be replaced with the URL of the `public` folder during the build.
              Only files inside the `public` folder can be referenced from the HTML.
              Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
              work correctly both with client-side routing and a non-root public URL.
              Learn how to configure a non-root public URL by running `npm run build`.
          -->
          <!-- Favicons for different devices --> */}
          <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png" />
          {/* <!--
              site.webmanifest provides metadata used when your web app is installed on a
              user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
          --> */}
          <link rel="manifest" href="favicon/site.webmanifest" />
```

2023-02-28 19:49 UTC, Panquesito7 requested changes

2023-02-28 19:49 UTC, Panquesito7 commented on src/pages/_document.tsx
>            <link rel="shortcut icon" href="favicon.ico" />
You should probably update the link to the favicon here.

2023-02-28 19:49 UTC, Panquesito7 commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Home | Design and Code" />
Shouldn't `Home` be the name of the current page instead?

2023-02-28 19:49 UTC, Panquesito7 commented on public/favicon/site.webmanifest
> +{"name":"Home | Design and Code","short_name":"DC","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"i
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
{"name":"Home | Design and Code","short_name":"DC","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color":"#ffffff","background_color":"#ffffff","display":"standalone"}

```

2023-03-01 03:01 UTC, Alkaison commented on public/favicon/site.webmanifest
> +{"name":"Home | Design and Code","short_name":"DC","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"i
Done ✅

2023-03-01 03:02 UTC, Alkaison commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Home | Design and Code" />
Removed it. Done ✅

2023-03-01 03:02 UTC, Alkaison commented on src/pages/_document.tsx
>            <link rel="shortcut icon" href="favicon.ico" />
Updated it to the favicon/favicon.ico file path

2023-03-01 20:43 UTC, Panquesito7 commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Design and Code" />
Shouldn't we add the name of the page the user is on?
For example: if it's the documentation page, use `Documentation | Design and Code`.

Also, I'm not 100% sure we want to add meta tags to all websites. 🤔 
CC: @Design-and-Code/project-maintainers.

2023-03-02 02:03 UTC, Alkaison commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Design and Code" />
- Content of this file **__documents.tsx_** will be applied to all webpages. 

- So we don't need to add the names of the pages like home, contact, documentation to meta tag because every page contain their own title tag.

- meta tags helps in ranking our website on top in search results and improves indexing stats of the contents.

- you should definitely add them!

2023-03-02 04:39 UTC, Panquesito7 commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Design and Code" />
Cool, thanks. :)
However, isn't there a way of obtaining the title of the current webpage the user is visiting? There should be a way to do so, as it's on the `_document.tsx` file, and then we can properly apply the title of each page.

2023-03-02 05:15 UTC, Alkaison commented on src/pages/_document.tsx
> +          <meta property="og:title" content="Design and Code" />
- I guess there should be a way to do that. I will try to implement it today.

- other than that is the **PR** ready for merge? @Panquesito7

2023-03-02 10:18 UTC, Alkaison commented
- I had try hard to add that feature of title attribute content using auto detect but its causing errors.
- I request you to merge this **`PR`** for **`meta tags improvement`**.
- I will create a new PR later for that feature and will work on it.

**Thanks!**

2023-03-02 23:25 UTC, Panquesito7 commented on src/pages/_document.tsx
> +};
```suggestion
};

```

2023-03-02 23:26 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-03-08 02:45 UTC, Alkaison commented
- 5 days passed and no response from review team. 😑
- Will this PR ever be merged ?

2023-03-08 02:53 UTC, Panquesito7 commented
> * 5 days passed and no response from review team. 😑
> * Will this PR ever be merged ?

1. Please be patient. The review team is busy with much other stuff.
2. It will once it is approved by the other maintainers.

2023-03-08 14:42 UTC, merged

2023-03-08 14:42 UTC, Greeshma2903 commented
Sorry for the delays, merged 🙌🏽 Thank you for contributing!

2023-03-08 17:19 UTC, Alkaison commented
- Thanks a lot!